version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    hostname: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
    - db_data:/var/lib/mysql
    # networks:
    # - carbird-cloud-network
    environment:
      MYSQL_DATABASE: 'text'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
    - '3306:3306'
    #expose:
    #- '3306'
    # volumes:
    #   - db_data:/var/lib/mysql

volumes:
  db_data:

# networks:
#   carbird-cloud-network:
#     external: true
